a=[2,3,4.6,"ab","cd"]
print(a)
print(type(a))
print(len(a))
print(a[-1])
print(a[::-1])
print(a[1:2])
print(a[0:4:2])
print(a[1:])
a[1]=["Apple"]
a[2]="cds"
print(a)
a.append("cbc")
print(a)
a.insert(2,3)
print(a)
a.extend([2,3,4.7,"abcs"])
print(a)